[package]
name        = "deepmail-body"
version.workspace     = true
edition.workspace     = true
authors.workspace     = true
license.workspace     = true
description = "DeepMail service: body"

[[bin]]
name = "deepmail-body"
path = "src/main.rs"

[dependencies]
deepmail-common = { path = "../deepmail-common" }

tokio.workspace              = true
tracing.workspace            = true
tracing-subscriber.workspace = true
anyhow.workspace             = true
