//! DeepMail service stub.
//!
//! This binary is generated by scripts/init_workspace.sh and exists so that
//! the Cargo workspace resolves cleanly while the real service is being
//! implemented. Replace this with the real entrypoint when ready.

fn main() {
    println!("deepmail service stub: not yet implemented");
}
