use crate::assembler::ReportData;
use crate::error::ReportError;
use std::fmt::Write;

pub fn render_json(report: &ReportData) -> Result<Vec<u8>, ReportError> {
    serde_json::to_vec_pretty(report).map_err(|e| ReportError::RenderError(e.to_string()))
}

pub fn render_html(report: &ReportData) -> Vec<u8> {
    let mut html = String::with_capacity(16_384);

    let verdict_color = match report.final_verdict.as_str() {
        "CLEAN" => "#27ae60",
        "LOW_RISK" => "#2980b9",
        "SUSPICIOUS" => "#e67e22",
        "PHISHING" => "#e74c3c",
        "MALICIOUS" => "#8e1200",
        _ => "#7f8c8d",
    };

    let _ = write!(
        html,
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>DeepMail Report — {email_id}</title>
<style>
*{{margin:0;padding:0;box-sizing:border-box}}
body{{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#f5f6fa;color:#2c3e50;line-height:1.6}}
.wrap{{max-width:960px;margin:0 auto;padding:24px}}
.header{{background:{verdict_color};color:#fff;padding:24px 32px;border-radius:8px 8px 0 0}}
.header h1{{font-size:22px;font-weight:600}}
.header .meta{{opacity:0.85;font-size:13px;margin-top:4px}}
.badge{{display:inline-block;padding:4px 14px;border-radius:12px;font-size:13px;font-weight:600;color:#fff;background:{verdict_color}}}
.card{{background:#fff;border:1px solid #e1e4e8;border-radius:6px;margin:16px 0;overflow:hidden}}
.card-head{{padding:12px 16px;font-weight:600;border-bottom:1px solid #e1e4e8;display:flex;justify-content:space-between;align-items:center}}
.card-body{{padding:16px}}
table{{width:100%;border-collapse:collapse}}
th,td{{text-align:left;padding:8px 12px;border-bottom:1px solid #f0f0f0;font-size:14px}}
th{{font-weight:600;background:#fafbfc}}
.bar-wrap{{width:120px;height:8px;background:#ecf0f1;border-radius:4px;display:inline-block;vertical-align:middle}}
.bar{{height:100%;border-radius:4px}}
.bar-low{{background:#27ae60}}.bar-med{{background:#e67e22}}.bar-high{{background:#e74c3c}}
details{{margin:8px 0}}
summary{{cursor:pointer;font-weight:600;padding:8px 0;font-size:14px}}
.tag-clean{{color:#27ae60}}.tag-suspicious{{color:#e67e22}}.tag-malicious{{color:#e74c3c}}.tag-unknown{{color:#7f8c8d}}
.footer{{text-align:center;padding:24px;color:#95a5a6;font-size:12px}}
.truncate{{max-width:300px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;display:inline-block;vertical-align:bottom}}
@keyframes pulse{{0%,100%{{opacity:1}}50%{{opacity:.7}}}}
.pulse{{animation:pulse 2s infinite}}
</style>
</head>
<body>
<div class="wrap">
<div class="header">
<h1>DeepMail Threat Report</h1>
<div class="meta">Email: {email_id} &bull; Tenant: {tenant_id} &bull; Generated: {generated_at}</div>
</div>
"#,
        email_id = esc(&report.email_id.to_string()),
        tenant_id = esc(&report.tenant_id.to_string()),
        generated_at = report.generated_at.format("%Y-%m-%d %H:%M:%S UTC"),
        verdict_color = verdict_color,
    );

    write_verdict_card(&mut html, report, verdict_color);
    write_metadata_card(&mut html, report);
    write_signal_table(&mut html, report);

    if let Some(ref h) = report.header_analysis {
        write_header_section(&mut html, h);
    }
    if let Some(ref d) = report.dkim_analysis {
        write_dkim_section(&mut html, d);
    }
    if let Some(ref g) = report.geo_analysis {
        write_geo_section(&mut html, g);
    }
    if let Some(ref ip) = report.ip_analysis {
        write_ip_section(&mut html, ip);
    }
    if let Some(ref intel) = report.intel_enrichment {
        write_intel_section(&mut html, intel);
    }
    if let Some(ref ioc) = report.ioc_analysis {
        write_ioc_section(&mut html, ioc);
    }
    if let Some(ref hom) = report.homograph_analysis {
        write_homograph_section(&mut html, hom);
    }
    if let Some(ref b) = report.body_analysis {
        write_body_section(&mut html, b);
    }
    if let Some(ref su) = report.sandbox_url {
        write_sandbox_url_section(&mut html, su);
    }
    if let Some(ref sf) = report.sandbox_file {
        write_sandbox_file_section(&mut html, sf);
    }
    if let Some(ref sd) = report.sandbox_dynamic {
        write_sandbox_dynamic_section(&mut html, sd);
    }

    let _ = write!(
        html,
        r#"<div class="footer">Generated by DeepMail &bull; {}</div>
</div></body></html>"#,
        report.generated_at.format("%Y-%m-%d %H:%M:%S UTC")
    );

    html.into_bytes()
}

fn esc(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#x27;")
}

fn score_bar(score: f32) -> String {
    let pct = (score * 100.0).clamp(0.0, 100.0);
    let class = if pct < 30.0 {
        "bar-low"
    } else if pct < 60.0 {
        "bar-med"
    } else {
        "bar-high"
    };
    format!(
        r#"<span class="bar-wrap"><span class="bar {class}" style="width:{pct:.0}%"></span></span> {score:.2}"#,
        class = class,
        pct = pct,
        score = score,
    )
}

fn truncate_url(url: &str, max: usize) -> String {
    if url.len() <= max {
        esc(url)
    } else {
        let mut s = esc(&url[..max]);
        s.push_str("&hellip;");
        s
    }
}

fn threat_tag(level: &str) -> &'static str {
    match level {
        "CLEAN" => "tag-clean",
        "SUSPICIOUS" | "LOW_RISK" => "tag-suspicious",
        "MALICIOUS" | "PHISHING" => "tag-malicious",
        _ => "tag-unknown",
    }
}

fn detail_open(score: f32) -> &'static str {
    if score > 0.5 { " open" } else { "" }
}

fn write_verdict_card(html: &mut String, report: &ReportData, color: &str) {
    let _ = write!(
        html,
        r#"<div class="card"><div class="card-head">Verdict<span class="badge" style="background:{color}">{verdict}</span></div>
<div class="card-body"><table>
<tr><td>Final Score</td><td>{bar}</td></tr>
<tr><td>Signals Available</td><td>{signals}</td></tr>
</table></div></div>
"#,
        color = color,
        verdict = esc(&report.final_verdict),
        bar = score_bar(report.final_score),
        signals = report.signals_available,
    );
}

fn write_metadata_card(html: &mut String, report: &ReportData) {
    let m = &report.email_metadata;
    let _ = write!(html, r#"<div class="card"><div class="card-head">Email Metadata</div><div class="card-body"><table>"#);
    if let Some(ref v) = m.subject {
        let _ = write!(html, "<tr><td>Subject</td><td>{}</td></tr>", esc(v));
    }
    if let Some(ref v) = m.from {
        let _ = write!(html, "<tr><td>From</td><td>{}</td></tr>", esc(v));
    }
    if let Some(ref v) = m.date_sent {
        let _ = write!(html, "<tr><td>Date</td><td>{}</td></tr>", v.format("%Y-%m-%d %H:%M:%S UTC"));
    }
    if let Some(ref v) = m.message_id {
        let _ = write!(html, "<tr><td>Message-ID</td><td>{}</td></tr>", esc(v));
    }
    if let Some(ref v) = m.reply_to {
        let _ = write!(html, "<tr><td>Reply-To</td><td>{}</td></tr>", esc(v));
    }
    if let Some(ref v) = m.return_path {
        let _ = write!(html, "<tr><td>Return-Path</td><td>{}</td></tr>", esc(v));
    }
    let _ = write!(html, "</table></div></div>\n");
}

fn write_signal_table(html: &mut String, report: &ReportData) {
    let _ = write!(
        html,
        r#"<div class="card"><div class="card-head">Signal Breakdown</div><div class="card-body"><table>
<tr><th>Signal</th><th>Score</th></tr>"#,
    );

    let signals: Vec<(&str, Option<f32>)> = vec![
        ("Header", report.header_analysis.as_ref().map(|_| section_score(report, "header"))),
        ("DKIM", report.dkim_analysis.as_ref().map(|d| d.replay_confidence)),
        ("Geo", report.geo_analysis.as_ref().map(|_| section_score(report, "geo"))),
        ("IP", report.ip_analysis.as_ref().map(|ip| ip.max_threat_score)),
        ("Intel", report.intel_enrichment.as_ref().map(|i| i.max_vt_score)),
        ("IOC", report.ioc_analysis.as_ref().map(|_| section_score(report, "ioc"))),
        ("Homograph", report.homograph_analysis.as_ref().map(|_| section_score(report, "homograph"))),
        ("Body", report.body_analysis.as_ref().map(|b| b.final_phishing_score)),
        ("Sandbox URL", report.sandbox_url.as_ref().map(|_| section_score(report, "sandbox_url"))),
        ("Sandbox File", report.sandbox_file.as_ref().map(|_| section_score(report, "sandbox_file"))),
        ("Sandbox Dynamic", report.sandbox_dynamic.as_ref().map(|_| section_score(report, "sandbox_dynamic"))),
    ];

    for (name, score) in signals {
        match score {
            Some(s) => {
                let _ = write!(html, "<tr><td>{}</td><td>{}</td></tr>", name, score_bar(s));
            }
            None => {
                let _ = write!(html, "<tr><td>{}</td><td style=\"color:#95a5a6\">N/A</td></tr>", name);
            }
        }
    }

    let _ = write!(html, "</table></div></div>\n");
}

fn section_score(_report: &ReportData, _name: &str) -> f32 {
    0.0
}

fn write_header_section(html: &mut String, h: &crate::assembler::HeaderAnalysisData) {
    let score = if h.return_path_mismatch || h.reply_to_mismatch { 0.7 } else { 0.2 };
    let _ = write!(
        html,
        r#"<details{open}><summary>Header Analysis</summary><div class="card"><div class="card-body"><table>
<tr><td>SPF</td><td>{spf}</td></tr>
<tr><td>DKIM</td><td>{dkim}</td></tr>
<tr><td>DMARC</td><td>{dmarc}</td></tr>
<tr><td>Return-Path Mismatch</td><td>{rp}</td></tr>
<tr><td>Reply-To Mismatch</td><td>{rt}</td></tr>
<tr><td>Hop Count</td><td>{hops}</td></tr>
</table>"#,
        open = detail_open(score),
        spf = esc(h.spf_result.as_deref().unwrap_or("N/A")),
        dkim = esc(h.dkim_result.as_deref().unwrap_or("N/A")),
        dmarc = esc(h.dmarc_result.as_deref().unwrap_or("N/A")),
        rp = if h.return_path_mismatch { "Yes" } else { "No" },
        rt = if h.reply_to_mismatch { "Yes" } else { "No" },
        hops = h.hop_count,
    );

    if !h.findings.is_empty() {
        let _ = write!(html, "<h4 style=\"margin:12px 0 4px\">Findings</h4><ul>");
        for f in &h.findings {
            let _ = write!(html, "<li>{}</li>", esc(f));
        }
        let _ = write!(html, "</ul>");
    }

    let _ = write!(html, "</div></div></details>\n");
}

fn write_dkim_section(html: &mut String, d: &crate::assembler::DkimAnalysisData) {
    let _ = write!(
        html,
        r#"<details{open}><summary>DKIM Analysis</summary><div class="card"><div class="card-body"><table>
<tr><td>Replay Confidence</td><td>{bar}</td></tr>
<tr><td>Verdict</td><td>{verdict}</td></tr>
</table>"#,
        open = detail_open(d.replay_confidence),
        bar = score_bar(d.replay_confidence),
        verdict = esc(&d.verdict),
    );

    if !d.signatures.is_empty() {
        let _ = write!(html, r#"<table style="margin-top:8px"><tr><th>Selector</th><th>Domain</th><th>Body Hash</th></tr>"#);
        for sig in &d.signatures {
            let _ = write!(
                html,
                "<tr><td>{}</td><td>{}</td><td>{}</td></tr>",
                esc(&sig.selector),
                esc(&sig.domain),
                if sig.body_hash_match { "Match" } else { "Mismatch" }
            );
        }
        let _ = write!(html, "</table>");
    }

    let _ = write!(html, "</div></div></details>\n");
}

fn write_geo_section(html: &mut String, g: &crate::assembler::GeoAnalysisData) {
    let score: f32 = match g.overall_risk.as_str() {
        "HIGH" | "CRITICAL" => 0.8,
        "MEDIUM" => 0.5,
        _ => 0.2,
    };
    let _ = write!(
        html,
        r#"<details{open}><summary>Geo Analysis</summary><div class="card"><div class="card-body"><table>
<tr><td>Origin IP</td><td>{ip}</td></tr>
<tr><td>Origin Country</td><td>{country}</td></tr>
<tr><td>Overall Risk</td><td>{risk}</td></tr>
</table>"#,
        open = detail_open(score),
        ip = esc(g.origin_ip.as_deref().unwrap_or("N/A")),
        country = esc(g.origin_country.as_deref().unwrap_or("N/A")),
        risk = esc(&g.overall_risk),
    );

    if !g.hops.is_empty() {
        let _ = write!(html, r#"<table style="margin-top:8px"><tr><th>IP</th><th>Country</th><th>Tor</th><th>VPN</th></tr>"#);
        for hop in &g.hops {
            let _ = write!(
                html,
                "<tr><td>{}</td><td>{}</td><td>{}</td><td>{}</td></tr>",
                esc(&hop.ip),
                esc(hop.country.as_deref().unwrap_or("N/A")),
                if hop.is_tor { "Yes" } else { "No" },
                if hop.is_vpn { "Yes" } else { "No" },
            );
        }
        let _ = write!(html, "</table>");
    }

    let _ = write!(html, "</div></div></details>\n");
}

fn write_ip_section(html: &mut String, ip: &crate::assembler::IpAnalysisData) {
    let _ = write!(
        html,
        r#"<details{open}><summary>IP Analysis</summary><div class="card"><div class="card-body"><table>
<tr><td>Max Threat Score</td><td>{bar}</td></tr>
<tr><td>Verdict</td><td>{verdict}</td></tr>
<tr><td>Analyzed IPs</td><td>{ips}</td></tr>
</table>"#,
        open = detail_open(ip.max_threat_score),
        bar = score_bar(ip.max_threat_score),
        verdict = esc(&ip.max_verdict),
        ips = esc(&ip.analyzed_ips.join(", ")),
    );

    if !ip.feed_hits.is_empty() {
        let _ = write!(html, "<p style=\"margin-top:8px\"><strong>Feed Hits:</strong> {}</p>", esc(&ip.feed_hits.join(", ")));
    }

    let _ = write!(html, "</div></div></details>\n");
}

fn write_intel_section(html: &mut String, i: &crate::assembler::IntelEnrichmentData) {
    let _ = write!(
        html,
        r#"<details{open}><summary>Threat Intel Enrichment</summary><div class="card"><div class="card-body"><table>
<tr><td>IOCs Analyzed</td><td>{analyzed}</td></tr>
<tr><td>Max VT Score</td><td>{bar}</td></tr>
<tr><td>Malicious IOCs</td><td>{malicious}</td></tr>
<tr><td>Provider Hits</td><td>{providers}</td></tr>
</table></div></div></details>
"#,
        open = detail_open(i.max_vt_score),
        analyzed = i.iocs_analyzed,
        bar = score_bar(i.max_vt_score),
        malicious = i.malicious_iocs,
        providers = esc(&i.provider_hits.join(", ")),
    );
}

fn write_ioc_section(html: &mut String, ioc: &crate::assembler::IocAnalysisData) {
    let score: f32 = if ioc.malicious_count > 0 { 0.9 } else if ioc.suspicious_count > 0 { 0.6 } else { 0.1 };
    let _ = write!(
        html,
        r#"<details{open}><summary>IOC Analysis</summary><div class="card"><div class="card-body"><table>
<tr><td>Total IOCs</td><td>{total}</td></tr>
<tr><td>Malicious</td><td><span class="tag-malicious">{mal}</span></td></tr>
<tr><td>Suspicious</td><td><span class="tag-suspicious">{sus}</span></td></tr>"#,
        open = detail_open(score),
        total = ioc.total_iocs,
        mal = ioc.malicious_count,
        sus = ioc.suspicious_count,
    );

    if let Some(ref name) = ioc.campaign_name {
        let _ = write!(
            html,
            "<tr><td>Campaign</td><td>{} ({})</td></tr>",
            esc(name),
            esc(ioc.campaign_status.as_deref().unwrap_or("UNKNOWN")),
        );
    }

    let _ = write!(html, "</table>");

    if !ioc.top_iocs.is_empty() {
        let _ = write!(
            html,
            r#"<table style="margin-top:8px"><tr><th>Type</th><th>Value</th><th>Threat</th><th>Score</th></tr>"#
        );
        for t in &ioc.top_iocs {
            let _ = write!(
                html,
                r#"<tr><td>{}</td><td class="truncate">{}</td><td class="{}">{}</td><td>{}</td></tr>"#,
                esc(&t.ioc_type),
                truncate_url(&t.value, 80),
                threat_tag(&t.threat_level),
                esc(&t.threat_level),
                score_bar(t.score),
            );
        }
        let _ = write!(html, "</table>");
    }

    let _ = write!(html, "</div></div></details>\n");
}

fn write_homograph_section(html: &mut String, h: &crate::assembler::HomographAnalysisData) {
    let score: f32 = if h.high_risk_count > 0 { 0.8 } else { 0.1 };
    let _ = write!(
        html,
        r#"<details{open}><summary>Homograph Analysis</summary><div class="card"><div class="card-body"><table>
<tr><td>Domains Checked</td><td>{checked}</td></tr>
<tr><td>High Risk</td><td>{high}</td></tr>
<tr><td>Overall Risk</td><td>{risk}</td></tr>
</table>"#,
        open = detail_open(score),
        checked = h.domains_checked,
        high = h.high_risk_count,
        risk = esc(&h.overall_risk),
    );

    if !h.suspicious_domains.is_empty() {
        let _ = write!(
            html,
            r#"<table style="margin-top:8px"><tr><th>Domain</th><th>Best Match</th><th>Score</th><th>Risk</th></tr>"#
        );
        for d in &h.suspicious_domains {
            let _ = write!(
                html,
                "<tr><td>{}</td><td>{}</td><td>{}</td><td>{}</td></tr>",
                esc(&d.domain),
                esc(&d.best_match),
                score_bar(d.score),
                esc(&d.risk),
            );
        }
        let _ = write!(html, "</table>");
    }

    let _ = write!(html, "</div></div></details>\n");
}

fn write_body_section(html: &mut String, b: &crate::assembler::BodyAnalysisData) {
    let _ = write!(
        html,
        r#"<details{open}><summary>Body Analysis</summary><div class="card"><div class="card-body"><table>
<tr><td>Verdict</td><td>{verdict}</td></tr>
<tr><td>Phishing Score</td><td>{bar}</td></tr>
<tr><td>URLs Found</td><td>{urls}</td></tr>
<tr><td>Shortener URLs</td><td>{short}</td></tr>
<tr><td>QR Codes</td><td>{qr}</td></tr>
<tr><td>Obfuscation</td><td>{obf}</td></tr>
<tr><td>Tracking Pixels</td><td>{tp}</td></tr>
</table>"#,
        open = detail_open(b.final_phishing_score),
        verdict = esc(&b.verdict),
        bar = score_bar(b.final_phishing_score),
        urls = b.url_count,
        short = b.shortener_url_count,
        qr = b.qr_code_count,
        obf = if b.has_obfuscation { "Detected" } else { "None" },
        tp = if b.has_tracking_pixels { "Detected" } else { "None" },
    );

    if !b.suspicious_urls.is_empty() {
        let _ = write!(html, "<h4 style=\"margin:12px 0 4px\">Suspicious URLs</h4><ul>");
        for u in &b.suspicious_urls {
            let _ = write!(html, "<li class=\"truncate\">{}</li>", truncate_url(u, 80));
        }
        let _ = write!(html, "</ul>");
    }

    let _ = write!(html, "</div></div></details>\n");
}

fn write_sandbox_url_section(html: &mut String, su: &crate::assembler::SandboxUrlData) {
    let score: f32 = if su.malicious_count > 0 { 0.9 } else { 0.2 };
    let _ = write!(
        html,
        r#"<details{open}><summary>URL Sandbox</summary><div class="card"><div class="card-body"><table>
<tr><td>Jobs Run</td><td>{jobs}</td></tr>
<tr><td>Malicious</td><td>{mal}</td></tr>
</table>"#,
        open = detail_open(score),
        jobs = su.jobs_run,
        mal = su.malicious_count,
    );

    if !su.reports.is_empty() {
        let _ = write!(
            html,
            r#"<table style="margin-top:8px"><tr><th>URL</th><th>Final URL</th><th>Threat</th><th>Score</th></tr>"#,
        );
        for r in &su.reports {
            let _ = write!(
                html,
                r#"<tr><td class="truncate">{}</td><td class="truncate">{}</td><td>{}</td><td>{}</td></tr>"#,
                truncate_url(&r.url, 60),
                truncate_url(r.final_url.as_deref().unwrap_or("-"), 60),
                esc(&r.threat_class),
                score_bar(r.score),
            );
        }
        let _ = write!(html, "</table>");
    }

    let _ = write!(html, "</div></div></details>\n");
}

fn write_sandbox_file_section(html: &mut String, sf: &crate::assembler::SandboxFileData) {
    let score: f32 = if sf.malicious_count > 0 { 0.9 } else { 0.2 };
    let _ = write!(
        html,
        r#"<details{open}><summary>File Sandbox</summary><div class="card"><div class="card-body"><table>
<tr><td>Attachments Analyzed</td><td>{total}</td></tr>
<tr><td>Malicious</td><td>{mal}</td></tr>
</table>"#,
        open = detail_open(score),
        total = sf.attachments_analyzed,
        mal = sf.malicious_count,
    );

    if !sf.reports.is_empty() {
        let _ = write!(
            html,
            r#"<table style="margin-top:8px"><tr><th>Filename</th><th>Verdict</th><th>Macros</th><th>YARA</th></tr>"#,
        );
        for r in &sf.reports {
            let _ = write!(
                html,
                "<tr><td>{}</td><td>{}</td><td>{}</td><td>{}</td></tr>",
                esc(&r.filename),
                esc(&r.verdict),
                if r.has_macros { "Yes" } else { "No" },
                esc(&r.yara_matches.join(", ")),
            );
        }
        let _ = write!(html, "</table>");
    }

    let _ = write!(html, "</div></div></details>\n");
}

fn write_sandbox_dynamic_section(html: &mut String, sd: &crate::assembler::SandboxDynamicData) {
    let score: f32 = if sd.malicious_count > 0 { 0.9 } else { 0.2 };
    let _ = write!(
        html,
        r#"<details{open}><summary>Dynamic Sandbox</summary><div class="card"><div class="card-body"><table>
<tr><td>Attachments Analyzed</td><td>{total}</td></tr>
<tr><td>Malicious</td><td>{mal}</td></tr>
</table>"#,
        open = detail_open(score),
        total = sd.attachments_analyzed,
        mal = sd.malicious_count,
    );

    if !sd.reports.is_empty() {
        let _ = write!(
            html,
            r#"<table style="margin-top:8px"><tr><th>File</th><th>Verdict</th><th>Malscore</th><th>C2 Hosts</th><th>Persistence</th></tr>"#,
        );
        for r in &sd.reports {
            let _ = write!(
                html,
                "<tr><td>{}</td><td>{}</td><td>{}</td><td>{}</td><td>{}</td></tr>",
                esc(&r.filename),
                esc(&r.verdict),
                score_bar(r.malscore),
                esc(&r.network_hosts.join(", ")),
                esc(&r.persistence.join(", ")),
            );
        }
        let _ = write!(html, "</table>");
    }

    let _ = write!(html, "</div></div></details>\n");
}
