[package]
name        = "deepmail-sandbox-url"
version.workspace     = true
edition.workspace     = true
authors.workspace     = true
license.workspace     = true
description = "DeepMail service: URL behavioral sandbox"

[[bin]]
name = "deepmail-sandbox-url"
path = "src/main.rs"

[dependencies]
deepmail-common = { path = "../deepmail-common" }

tokio.workspace              = true
tonic.workspace              = true
prost.workspace              = true
sqlx.workspace               = true
async-nats.workspace         = true
serde.workspace              = true
serde_json.workspace         = true
tracing.workspace            = true
tracing-subscriber.workspace = true
thiserror.workspace          = true
anyhow.workspace             = true
uuid.workspace               = true
chrono.workspace             = true
futures.workspace             = true
once_cell.workspace          = true
reqwest = { workspace = true }

bollard = "0.17"
base64 = "0.22"
tonic-health = "0.11"
which = "8"
tempfile = "3"
url = "2"
aws-config = { version = "1", features = ["behavior-version-latest"] }
aws-sdk-s3 = "1"
