[package]
name        = "deepmail-otp-smtp"
version.workspace     = true
edition.workspace     = true
authors.workspace     = true
license.workspace     = true
description = "DeepMail service: otp-smtp"

[[bin]]
name = "deepmail-otp-smtp"
path = "src/main.rs"

[dependencies]
deepmail-common = { path = "../deepmail-common" }

tokio.workspace              = true
tracing.workspace            = true
tracing-subscriber.workspace = true
anyhow.workspace             = true
tonic.workspace              = true
serde.workspace              = true
thiserror.workspace          = true
config.workspace             = true
uuid.workspace               = true
lettre = { version = "0.11", default-features = false, features = ["tokio1-rustls-tls", "smtp-transport", "builder", "pool", "hostname"] }
