[package]
name        = "deepmail-report"
version.workspace     = true
edition.workspace     = true
authors.workspace     = true
license.workspace     = true
description = "DeepMail service: report generation (JSON + HTML)"

[[bin]]
name = "deepmail-report"
path = "src/main.rs"

[dependencies]
deepmail-common = { path = "../deepmail-common" }

tokio.workspace              = true
tonic.workspace              = true
prost.workspace              = true
axum.workspace               = true
sqlx.workspace               = true
async-nats.workspace         = true
serde.workspace              = true
serde_json.workspace         = true
tracing.workspace            = true
tracing-subscriber.workspace = true
thiserror.workspace          = true
anyhow.workspace             = true
uuid.workspace               = true
chrono.workspace             = true
futures.workspace             = true
tower-http.workspace         = true

tonic-health = "0.11"
aws-config = { version = "1", features = ["behavior-version-latest"] }
aws-sdk-s3 = "1"
aws-credential-types = { version = "1", features = ["hardcoded-credentials"] }
