[package]
name        = "deepmail-intel"
version.workspace     = true
edition.workspace     = true
authors.workspace     = true
license.workspace     = true
description = "DeepMail service: intel"

[[bin]]
name = "deepmail-intel"
path = "src/main.rs"

[dependencies]
deepmail-common = { path = "../deepmail-common" }

tokio.workspace              = true
tracing.workspace            = true
tracing-subscriber.workspace = true
anyhow.workspace             = true
