#!/usr/bin/env bash
# init_workspace.sh
#
# Idempotently scaffolds the 22 non-common DeepMail crates so that
# `cargo check --workspace` succeeds even before any service is implemented.
#
# - Each crate is created as a [[bin]] with a stub src/main.rs.
# - Each crate's Cargo.toml inherits version/edition/authors/license from
#   the workspace and depends on deepmail-common via path.
# - Files are only written when they do not already exist.
#
# Usage:
#   bash scripts/init_workspace.sh
#
# Run from anywhere; this script cd's to the workspace root.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
WORKSPACE_ROOT="$(cd -- "${SCRIPT_DIR}/.." &> /dev/null && pwd)"
cd "${WORKSPACE_ROOT}"

# All 22 non-common crates. deepmail-common is hand-authored and must
# already exist; this script will not touch it.
CRATES=(
    deepmail-gateway
    deepmail-auth
    deepmail-tenant
    deepmail-ingest
    deepmail-parser
    deepmail-otp-smtp
    deepmail-header
    deepmail-dkim
    deepmail-geo
    deepmail-ip
    deepmail-intel
    deepmail-ioc
    deepmail-homograph
    deepmail-body
    deepmail-sandbox-url
    deepmail-sandbox-file
    deepmail-sandbox-dynamic
    deepmail-hashdb
    deepmail-scoring
    deepmail-graph
    deepmail-report
    deepmail-billing
    deepmail-notify
)

write_if_missing() {
    local path="$1"
    local body="$2"
    if [[ -e "${path}" ]]; then
        echo "  skip   ${path} (already exists)"
        return 0
    fi
    mkdir -p "$(dirname -- "${path}")"
    printf '%s' "${body}" > "${path}"
    echo "  write  ${path}"
}

echo "==> DeepMail workspace skeleton"
echo "    workspace root: ${WORKSPACE_ROOT}"

for crate in "${CRATES[@]}"; do
    crate_dir="crates/${crate}"
    mkdir -p "${crate_dir}/src"

    cargo_toml=$(cat <<EOF
[package]
name        = "${crate}"
version.workspace     = true
edition.workspace     = true
authors.workspace     = true
license.workspace     = true
description = "DeepMail service: ${crate#deepmail-}"

[[bin]]
name = "${crate}"
path = "src/main.rs"

[dependencies]
deepmail-common = { path = "../deepmail-common" }

tokio.workspace              = true
tracing.workspace            = true
tracing-subscriber.workspace = true
anyhow.workspace             = true
EOF
)

    main_rs=$(cat <<'EOF'
//! DeepMail service stub.
//!
//! This binary is generated by scripts/init_workspace.sh and exists so that
//! the Cargo workspace resolves cleanly while the real service is being
//! implemented. Replace this with the real entrypoint when ready.

fn main() {
    println!("deepmail service stub: not yet implemented");
}
EOF
)

    write_if_missing "${crate_dir}/Cargo.toml" "${cargo_toml}"$'\n'
    write_if_missing "${crate_dir}/src/main.rs" "${main_rs}"$'\n'
done

echo "==> done"
