syntax = "proto3";

package deepmail.report;

import "google/protobuf/timestamp.proto";

service ReportService {
  rpc GenerateReport (ReportRequest) returns (ReportResponse);
  rpc GetReport      (GetReportReq)  returns (ReportResponse);
}

enum ReportFormat {
  PDF      = 0;
  STIX_2_1 = 1;
  JSON     = 2;
  CSV      = 3;
}

message ReportRequest {
  string       email_id      = 1;
  string       tenant_id     = 2;
  string       requested_by  = 3;
  ReportFormat format        = 4;
}

message ReportResponse {
  string       report_id     = 1;
  ReportFormat format        = 2;
  string       s3_signed_url = 3;
  string       status        = 4;
  google.protobuf.Timestamp expires_at = 5;
  string       error         = 6;
}

message GetReportReq {
  string report_id = 1;
}
